[Metadata]
organism
sex
age
disease
ethnicity
tissue
assay
donor_id

[Candidate]
CD41
CD61

[Markers]
PPBP
GP6
PF4
CD40L
FCGR2A
CD42B
CD61
CD41

[Thresholds]
mean_expression_threshold = auto2

[Folder]
input_folder = /home/lemgui01/CellExtractor/data/raw
output_folder = ./output

[Optional]
species = hsapiens # species to use for gene name mapping
percent_top = 20 # percentage of top genes to consider for quality control metrics
nmads = 5 # number of median absolute deviations to consider as outliers