[Metadata]
organism
sex
age
disease
ethnicity
tissue
assay
donor_id

[Candidate]
CD41
CD61

[Markers]
PPBP
GP6
PF4
CD40L
FCGR2A
CD42B
CD61
CD41

[Thresholds]
mean_expression_threshold = auto

[Folder]
input_folder = ./input
output_folder = ./output
