[Metadata]
sex
age
disease
tissue
donor_id
cluster

[Candidate]
CD4
CD62L

[Markers]
CD4
CD62L
CCR7
CD44
IL7R

[Thresholds]
min_genes_detected = 2 # minimum number of candidate genes that must be detected
gene_detection_threshold = 1 # expression level threshold to consider a gene as detected
n_components = 2 # number of components for Gaussian Mixture Model

[Folder]
input_folder = /home/lemgui01/CellExtractor/data/raw_mouse
output_folder = /home/lemgui01/CellExtractor/data/results_lympho_2-1

[Options]
species = mmusculus # species to use for gene name pybiomart mapping (hsapiens, mmusculus, etc)
percent_top = 20 # percentage of top genes to consider for quality control metrics
nmads = 5 # number of median absolute deviations to consider as outliers
plot_extracted = True # folder to save the plots