[Metadata]
sex
age
disease
tissue
donor_id
cell

[Candidate]
CD41
CD61

[Target]
PPBP
GP6
PF4
CD40L
FCGR2A
CD42B
CD61
CD41

[Monocytes]
S100A8
S100A9
CD14
LST1
CD36

[Macrophages]
MARCO
CD68
CD163
ITGAM
MRC1
MSR1

[Lymphocytes]
CD3D
CD3E
CD3G
CD3
CD4
CD8
CD45

[Neutrophils]
CD15
CD114
CEACAM8
CAMP
FPR1
FPR1

[Thresholds]
min_genes_detected = 1 # minimum number of candidate genes that must be detected
gene_detection_threshold = 1 # expression level threshold to consider a gene as detected
n_components_target = auto # number of components for the target Gaussian Mixture Model
n_components_exclu = auto # number of components for the excluded Gaussian Mixture Model
min_mean_expression = 2 # minimum mean expression level for the higher component can be considered as target cluster.

[Folder]
input_folder = /mnt/scratch/guillaume/data/pbmc_human
output_folder = /mnt/scratch/guillaume/results_pbmc_human

[Options]
species = hsapiens # species to use for gene name pybiomart mapping (hsapiens, mmusculus, etc)
percent_top = 20 # percentage of top genes to consider for quality control metrics
nmads = 5 # number of median absolute deviations to consider as outliers
do_QC = False # whether to perform quality control on the dataset (True/False)