[Metadata]
sex
age
disease
tissue
donor_id
cell

[Candidate]
CD41
CD61

[Markers]
PPBP
GP6
PF4
CD40L
FCGR2A
CD42B
CD61
CD41

[Exclude]

[Thresholds]
min_genes_detected = 2 # minimum number of candidate genes that must be detected
gene_detection_threshold = 1 # expression level threshold to consider a gene as detected
n_components_target = auto # number of components for the target Gaussian Mixture Model
n_components_exclu = auto # number of components for the excluded Gaussian Mixture Model

[Folder]
input_folder = /home/lemgui01/SIGMA/data/raw_human
output_folder = /home/lemgui01/SIGMA/data/results_mk_21

[Options]
species = hsapiens # species to use for gene name pybiomart mapping (hsapiens, mmusculus, etc)
percent_top = 20 # percentage of top genes to consider for quality control metrics
nmads = 5 # number of median absolute deviations to consider as outliers
do_QC = True # whether to perform quality control on the dataset (True/False)

