[Metadata]
sex
age
disease
tissue
donor_id
cell

[Candidate]
CD41
CD61

[Markers]
PPBP
GP6
PF4
CD40L
FCGR2A
CD42B
CD61
CD41

[Exclude]

[Thresholds]
min_genes_detected = 1 # minimum number of candidate genes that must be detected
gene_detection_threshold = 2 # expression level threshold to consider a gene as detected
n_components_target = auto # number of components for the target Gaussian Mixture Model
n_components_exclu = auto # number of components for the excluded Gaussian Mixture Model
min_mean_expression = 2 # minimum mean expression level for the higher component can be considered as target cluster

[Folder]
input_folder = /mnt/scratch/guillaume/SIGMA/data/raw_human
output_folder = /mnt/scratch/guillaume/SIGMA/data/results_mk_12

[Options]
species = hsapiens # species to use for gene name pybiomart mapping (hsapiens, mmusculus, etc)
percent_top = 20 # percentage of top genes to consider for quality control metrics
nmads = 5 # number of median absolute deviations to consider as outliers
do_QC = True # whether to perform quality control on the dataset (True/False)
