[Metadata]
sex
age
tissue
ethnicity
assay

[Candidate]
CD41
CD61

[Target]
PPBP
GP6
PF4
CD40L
FCGR2A
CD42B
CD61
CD41

[Monocytes]
CD14
CD163
FCN1
CCR2
FCGR3A

[Macrophages]
CD68
CCR5
F3
CD163
CD11b
CD14
LYZ
FCGR1A
ITGAM

[LymphocytesT]
CD3D
CD3E
CD3G
CD4
CD8A
CD8B
TCRA
TCRB
TCRD
TCRG

[LymphocytesB]
CD19
CD20
MS4A1
CD22
CD79A
CD79B
PAX5

[Neutrophils]
CD15
MPO
CSF3R
CXCR4
FCGR3B
CEACAM8
CD11b

[Thresholds]
min_genes_detected = 1 # Minimum number of candidate genes to detect to consider a cell as a candidate
gene_detection_threshold = 2 # Expression threshold to consider a gene as expressed
n_components_target = auto # number of components for the target Gaussian Mixture Model
n_components_exclu = auto # number of components for the excluded Gaussian Mixture Model
min_mean_expression = 2 # minimum mean expression level for the higher component can be considered as target cluster.

[Folder]
input_folder = /mnt/projects_tn03/Data_MK/these/mk_healthy
output_folder = /mnt/projects_tn03/AD_EB_singlecell/mk_healthy

[Options]
species = hsapiens # species to use for gene name pybiomart mapping (hsapiens, mmusculus, etc)
percent_top = 20 # percentage of top genes to consider for quality control metrics
nmads = 5 # number of median absolute deviations to consider as outliers
do_QC = False # whether to perform quality control on the dataset (True/False)
exclude_celltypes = True # True if you want to exclude  entire cell type(s), false if you want to exclude specific "low" genes.