[Metadata]
sex
age
tissue
ethnicity
assay

[Candidate]
ITGA2B
GP1BA

[Target]
ITGA2B
GP1BA
FCGR2A
CD40L
PF4
PPBP
GP6
CD42B

[Monocytes]
CD14
LYZ
FCN1
CCR2
FCGR1A

[Macrophages]
CD14
CD68
ITGAM
FCGR1A

[LymphocytesT]
CD3
CD4
CD8
TCRA
TCRB
TCRD
TCRG

[LymphocytesB]
CD19
CD20

[Neutrophils]
CD15
MPO
CSF3R
CXCR4
CD101
FCGR3B
CD11b

[Thresholds]
min_genes_detected = 1
gene_detection_threshold = 2
n_components_target = auto
n_components_exclu = auto
min_mean_expression = 2

[Folder]
input_folder = /mnt/scratch/guillaume/data/mk_sle
output_folder = /mnt/projects_tn03/AD_EB_singlecell/mk_sle

[Options]
species = hsapiens # species to use for gene name pybiomart mapping (hsapiens, mmusculus, etc)
percent_top = 20 # percentage of top genes to consider for quality control metrics
nmads = 5 # number of median absolute deviations to consider as outliers
do_QC = True # whether to perform quality control on the dataset (True/False)
exclude_celltypes = True # True if you want to exclude an entire cell type, False if you want to exclude specific "low" genes.