[Metadata]
donor
sex
age
celltype
organ
chemistry

[Candidate]
CD41
CD61

[Target]
PPBP
GP6
PF4
CD40L
FCGR2A
CD42B
CD61
CD41

[Monocytes]
CD14
LYZ
FCN1
CCR2
FCGR1A
# HLA-DRA # risque d'être des MKs immuns
# CD36 # risque d'être des MKs immuns

[Macrophages]
CD14
CD68
ITGAM
FCGR1A
# MSR1 # a verifier
# PTPRC # a verifier

[LymphocytesT]
CD3
CD4
CD8
TCRA
TCRB
TCRD
TCRG

[LymphocytesB]
CD19
CD20

[Neutrophils]
CD15
MPO
CSF3R
# CXCR2 # risque d'être des MKs
FCGR3B
CD11B
# S100A8 # risque d'être des MKs
# S100A9 # risque d'être des MKs
CXCR4
CD101

[Thresholds]
min_genes_detected = 1 # Minimum number of candidate genes to detect to consider a cell as a candidate
gene_detection_threshold = 2 # Expression threshold to consider a gene as expressed
n_components_target = 5 # number of components for the target Gaussian Mixture Model
n_components_exclu = auto # number of components for the excluded Gaussian Mixture Model
min_mean_expression = 2 # minimum mean expression level for the higher component can be considered as target cluster.

[Folder]
input_folder = /mnt/scratch/guillaume/data/fortman
output_folder = /mnt/scratch/guillaume/results_fortman

[Options]
species = hsapiens # species to use for gene name pybiomart mapping (hsapiens, mmusculus, etc)
percent_top = 20 # percentage of top genes to consider for quality control metrics
nmads = 5 # number of median absolute deviations to consider as outliers
do_QC = False # whether to perform quality control on the dataset (True/False)