[Metadata]
donor
sex
age
celltype
organ
chemistry
disease

[Candidate]
CD41
CD61

[Target]
PPBP
GP6
PF4
CD40L
FCGR2A
CD42B
CD61
CD41

[Monocytes]
CD14
LYZ
VCAN
FCN1
CCR2
FCGR3A

[Macrophages]
CD14
CD68
ITGAM
FCGR1A

[LymphocytesT]
CD3E
CD3D
CD3G
CD4
CD8A
CD8B
PTPRC

[LymphocytesB]
CD19
CD20
CD79A
PAX5
EBF1

[Neutrophils]
CD15
MPO
CSF3R
FCGR3B
CD11B
CXCR4
CD101

[Thresholds]
min_genes_detected = 2 # Minimum number of candidate genes to detect to consider a cell as a candidate
gene_detection_threshold = 2 # Expression threshold to consider a gene as expressed
n_components_target = auto # number of components for the target Gaussian Mixture Model
n_components_exclu = auto # number of components for the excluded Gaussian Mixture Model
min_mean_expression = 2 # minimum mean expression level for the higher component can be considered as target cluster.

[Folder]
input_folder = /mnt/projects_tn03/Data_MK/article/mk_fortman
output_folder = /mnt/projects_tn03/Data_MK/article/results_fortman

[Options]
species = hsapiens # species to use for gene name pybiomart mapping (hsapiens, mmusculus, etc)
percent_top = 20 # percentage of top genes to consider for quality control metrics
nmads = 5 # number of median absolute deviations to consider as outliers
do_QC = False # whether to perform quality control on the dataset (True/False)
exclude_celltypes = True # True if you want to exclude an entire cell type, false if you want to exclude specific "low" genes.