[Metadata]
celltype
disease

[Candidate]
CD41
CD61

[Target]
PPBP
GP6
PF4
CD40L
FCGR2A
CD42B
CD61
CD41

[Monocytes]
LST1
LYZ
CTSS
FCN1
VCAN
CD14
S100A8
S100A9
S100A12
FCGR3A
MS4A7
AIF1

[Macrophages]
CD68
CSF1R
FCGR1A
AIF1
CD163
MRC1
CX3CR1
C1QA
C1QB
C1QC
FCER1G
TYROBP

[LymphocytesT]
CD3D
CD3E
CD3G
TRAC
TRBC1
TRBC2
LTB
IL7R
CD4
CD8A
CD8B

[LymphocytesB]
MS4A1
CD79A
CD79B
CD19
CD74
HLA-DRA
CD37
BANK1
PAX5
CD22
HVCN1
BLNK

[Neutrophils]
S100A8
S100A9
S100A12
FCGR3B
CEACAM8
CXCR2
CSF3R
FUT4
PRTN3
CTSG
MPO
LCN2
CD177

[Thresholds]
min_genes_detected = 1 # Minimum number of candidate genes to detect to consider a cell as a candidate
gene_detection_threshold = 1 # Expression threshold to consider a gene as expressed
n_components_target = auto # number of components for the target Gaussian Mixture Model
n_components_exclu = auto # number of components for the excluded Gaussian Mixture Model
min_mean_expression = 2 # minimum mean expression level for the higher component can be considered as target cluster.

[Folder]
input_folder = input/Fortmann-Data
output_folder = output/results_Fortmann

[Options]
species = hsapiens # species to use for gene name pybiomart mapping (hsapiens, mmusculus, etc)
percent_top = 20 # percentage of top genes to consider for quality control metrics
nmads = 5 # number of median absolute deviations to consider as outliers
do_QC = False # whether to perform quality control on the dataset (True/False)
exclude_celltypes = True # True if you want to exclude entire cell type(s), false if you want to exclude "low" genes.