[Metadata]
donor
sex
age
celltype
organ
chemistry

[Candidate]
CD3E
CD3D
CD4
CD7

[Target]
CXCR5
PDCD1
BCL6
ICOS
CD4
IL21
SH2D1A
CXCL13
SLAMF6

[LowIn]
CCR7
SELL
S1PR1
GPR183
SELPLG
FOXP3

[Thresholds]
min_genes_detected = 2 # Minimum number of candidate genes to detect to consider a cell as a candidate
gene_detection_threshold = 2 # Expression threshold to consider a gene as expressed
n_components_target = auto # number of components for the target Gaussian Mixture Model
n_components_exclu = auto # number of components for the excluded Gaussian Mixture Model
min_mean_expression = 2 # minimum mean expression level for the higher component can be considered as target cluster.

[Folder]
input_folder = /mnt/projects_tn03/Data_MK/article/tfh_10xgenomics
output_folder = /mnt/projects_tn03/Data_MK/article/results_10xgenomics

[Options]
species = mmusculus # species to use for gene name pybiomart mapping (hsapiens, mmusculus, etc)
percent_top = 20 # percentage of top genes to consider for quality control metrics
nmads = 5 # number of median absolute deviations to consider as outliers
do_QC = False # whether to perform quality control on the dataset (True/False)
exclude_celltypes = False # True if you want to exclude an entire cell type, false if you want to exclude specific "low" genes.