[Metadata]
donor
sex
age
celltype
organ
chemistry

[Candidate]
CD3E
TRAC
CD8A
CD8B

[Target]
GZMK
GZMB
NKG7
PRF1
CX3CR1
IL7R
CD44

[LowIn]
CCR7
SELL
TCF7
LEF1
CXCR5
CD27
FOXP3
TRDC
TRGC1
TRGC2

[Thresholds]
min_genes_detected = 3 # Minimum number of candidate genes to detect to consider a cell as a candidate
gene_detection_threshold = 2 # Expression threshold to consider a gene as expressed
n_components_target = auto # number of components for the target Gaussian Mixture Model
n_components_exclu = auto # number of components for the excluded Gaussian Mixture Model
min_mean_expression = 2 # minimum mean expression level for the higher component can be considered as target cluster.

[Folder]
input_folder = /mnt/scratch/guillaume/data/tem_dominguez
output_folder = /mnt/scratch/guillaume/results_dominguez

[Options]
species = hsapiens # species to use for gene name pybiomart mapping (hsapiens, mmusculus, etc)
percent_top = 20 # percentage of top genes to consider for quality control metrics
nmads = 5 # number of median absolute deviations to consider as outliers
do_QC = True # whether to perform quality control on the dataset (True/False)
exclude_celltypes = False # True if you want to exclude an entire cell type, false if you want to exclude specific "low" genes.