[Metadata]
donor
sex
age
celltype
organ
chemistry

[Candidate]
CD41
CD61

[Target]
PPBP
GP6
PF4
CD40L
FCGR2A
CD42B
CD61
CD41

[Monocytes]
CD11b
CD14
CCR2
CD163
HLA-DR
CD115
CD62L

[Macrophages]
CD80
CD86
CCR5
CD11b
CD14
CD11c
CD15
CD68
CD163 
EMR1 
CD64
CD32
CD16
TLR2
TLR4
CD11a

[LymphocytesTRegulator]
CD3
CD4
CD5
CD25
CD39
CD103
CD134
CD223

[Neutrophils]
CD11b
CD15
CD16
CD32
CD33
CD44
CD45
CD66b

[Thresholds]
gene_detection_threshold = 2 # Expression threshold to consider a gene as expressed
min_genes_detected = 1 # Minimum number of candidate genes to detect to consider a cell as a candidate
n_components_target = auto # number of components for the target Gaussian Mixture Model
n_components_exclu = auto # number of components for the excluded Gaussian Mixture Model
min_mean_expression = 2 # minimum mean expression level for the higher component can be considered as target cluster.

[Folder]
input_folder = /mnt/scratch/guillaume/data/dominguez
output_folder = /mnt/scratch/guillaume/results_dominguez

[Options]
species = hsapiens # species to use for gene name pybiomart mapping (hsapiens, mmusculus, etc)
percent_top = 20 # percentage of top genes to consider for quality control metrics
nmads = 5 # number of median absolute deviations to consider as outliers
do_QC = False # whether to perform quality control on the dataset (True/False)